"""Emit montmul.bend: a 254-bit Montgomery multiplication over BN254 Fr with
16 x 16-bit limbs held in U32 (the only native integer; no U64, no mul-hi;
U32 mul wraps). One CIOS cell t + a*b + c <= (2^16-1)^2 + 2*(2^16-1) = 2^32-1
fits, so every partial product is exact. Fully unrolled SSA, R = 2^256.
Run: uv run python gen_montmul.py > montmul.bend"""
P = 21888242871839275222246405745257275088548364400416034343698204186575808495617
L = 16
B = 1 << 16
MASK = B - 1
plimbs = [(P >> (16 * j)) & MASK for j in range(L)]
n0inv = (-pow(P, -1, B)) % B
out = []
w = out.append
fresh = [0]
def new(expr):
    fresh[0] += 1
    v = "v%d" % fresh[0]
    w("  +%s = %s" % (v, expr))
    return v
w("# GENERATED by gen_montmul.py -- do not edit by hand.")
w("# Montgomery multiplication mod BN254 Fr, 16 x 16-bit limbs in U32, R = 2^256.")
w("# MODE=check: print CHECK (default 128) results for check_montmul.py to verify.")
w("# MODE=bench|gpu: 2^N independent products (fork depth FD, K chained muls each).")
w("import Base")
w("")
w("type Fr is Data:")
w("  Fr{" + ", ".join("+l%d: U32" % j for j in range(L)) + "}")
w("")
w("def h(+i: U32) -> U32:")
w("  (((i * 2654435761) .^. (i >> 15n)) * 2246822519 : U32)")
w("")
w("# pseudo-random field element below p: 16-bit limbs from h, top limb masked to 0x2FFF")
w("def rnd(+seed: U32) -> Fr:")
w("  Fr{" + ", ".join(("(h((seed + %d : U32)) .&. %d : U32)" % (j * 40503 + 1, 0x2FFF if j == L - 1 else MASK)) for j in range(L)) + "}")
w("")
w("def mont(a: Fr, b: Fr) -> Fr:")
w("  match a b:")
w("    case Fr{" + ", ".join("a%d" % j for j in range(L)) + "} Fr{" + ", ".join("b%d" % j for j in range(L)) + "}:")
# SSA body, indented 6
body = []
def emit(expr):
    fresh[0] += 1
    v = "v%d" % fresh[0]
    body.append("      +%s = %s" % (v, expr))
    return v
t = ["0"] * (L + 2)
for i in range(L):
    c = None
    for j in range(L):
        prod = "U32.mul(a%d, b%d)" % (j, i)
        s = "U32.add(%s, %s)" % (t[j], prod) if t[j] != "0" else prod
        if c is not None:
            s = "U32.add(%s, %s)" % (s, c)
        s = emit(s)
        t[j] = emit("U32.and(%s, 65535)" % s)
        c = emit("U32.shrn(%s, 16n)" % s)
    s = emit("U32.add(%s, %s)" % (t[L], c)) if t[L] != "0" else c
    t[L] = emit("U32.and(%s, 65535)" % s)
    t[L + 1] = emit("U32.shrn(%s, 16n)" % s)
    m = emit("U32.and(U32.mul(%s, %d), 65535)" % (t[0], n0inv))
    s = emit("U32.add(%s, U32.mul(%s, %d))" % (t[0], m, plimbs[0]))
    c = emit("U32.shrn(%s, 16n)" % s)
    for j in range(1, L):
        s = emit("U32.add(U32.add(%s, U32.mul(%s, %d)), %s)" % (t[j], m, plimbs[j], c))
        t[j - 1] = emit("U32.and(%s, 65535)" % s)
        c = emit("U32.shrn(%s, 16n)" % s)
    s = emit("U32.add(%s, %s)" % (t[L], c))
    t[L - 1] = emit("U32.and(%s, 65535)" % s)
    c = emit("U32.shrn(%s, 16n)" % s)
    t[L] = emit("U32.add(%s, %s)" % (t[L + 1], c))
    t[L + 1] = "0"
# conditional subtract: d = t - p; keep d when no final borrow (t >= p)
d = []
br = None
for j in range(L):
    s = "U32.sub(U32.add(%s, 65536), %d)" % (t[j], plimbs[j])
    if br is not None:
        s = "U32.sub(%s, %s)" % (s, br)
    s = emit(s)
    d.append(emit("U32.and(%s, 65535)" % s))
    br = emit("U32.sub(1, U32.shrn(%s, 16n))" % s)
# t[L] (the 2^256 carry) also cancels a borrow: t >= p iff t[L] == 1 or no borrow
ge = emit("U32.or(%s, U32.sub(1, %s))" % (t[L], br))  # 1 when t >= p
keep_t = emit("U32.sub(%s, 1)" % ge)  # 0xFFFFFFFF when t < p, 0 when t >= p
r = []
for j in range(L):
    r.append(emit("U32.or(U32.and(%s, %s), U32.and(%s, U32.not(%s)))" % (t[j], keep_t, d[j], keep_t)))
out.extend(body)
w("      Fr{" + ", ".join(r) + "}")
w("")
w("def Fr.lo(x: Fr) -> U32:")
w("  match x:")
w("    case Fr{" + ", ".join("l%d" % j for j in range(L)) + "}:")
w("      l0")
w("")
w("def Fr.show(x: Fr) -> String:")
w("  match x:")
w("    case Fr{" + ", ".join("l%d" % j for j in range(L)) + "}:")
w("      " + ' ++ "," ++ '.join("U32.show(l%d)" % j for j in range(L)))
w("")
w("# k chained products r <- mont(r, b)")
w("def chain(k: Nat, r: Fr, +b: Fr) -> Fr:")
w("  match k:")
w("    case 0n:")
w("      r")
w("    case 1n+p:")
w("      chain(p, mont(r, b), b)")
w("")
w("# sequential leaf: n products on distinct inputs, xor-folded on limb 0")
w("def leaf(n: Nat, +k: Nat, +i: U32, acc: U32) -> U32:")
w("  match n:")
w("    case 0n:")
w("      acc")
w("    case 1n+p:")
w("      leaf(p, k, (i + 1 : U32), (acc .^. Fr.lo(chain(k, rnd((i * 2 : U32)), rnd((i * 2 + 1 : U32)))) : U32))")
w("")
w("# fork tree: d levels, each leaf runs ln products")
w("def tree(d: Nat, +ln: Nat, +k: Nat, +i: U32, +w: U32) -> U32:")
w("  match d:")
w("    case 0n:")
w("      leaf(ln, k, i, 0)")
w("    case 1n++p:")
w("      +hw = (w >> 1n : U32)")
w("      a b = tree(p, ln, k, i, hw) tree(p, ln, k, (i + hw : U32), hw)")
w("      (a .^. b : U32)")
w("")
w("def check(n: Nat, +i: U32) -> IO(Unit):")
w("  match n:")
w("    case 0n:")
w("      IO.pure(Unit, Unit{})")
w("    case 1n+p:")
w("      do IO<Unit>:")
w("        IO.print(U32.show(i) ++ \" \" ++ Fr.show(mont(rnd((i * 2 : U32)), rnd((i * 2 + 1 : U32)))))")
w("        check(p, (i + 1 : U32))")
w("")
w("def env_nat.parse(m: Maybe<&2, U32>, +dflt: Nat) -> Nat:")
w("  match m:")
w("    case Some{v}:")
w("      U32.to_nat(v)")
w("    case None{}:")
w("      dflt")
w("")
w("def env_nat.fin(r: Result<&1, &1, U32 & String, String>, +dflt: Nat) -> Nat:")
w("  match r:")
w("    case Done{s}:")
w("      env_nat.parse(U32.read(s), dflt)")
w("    case Fail{e}:")
w("      dflt")
w("")
w("def env_nat(name: String, +dflt: Nat) -> IO(Nat):")
w("  do IO<Nat>:")
w("    r : Result<&1, &1, U32 & String, String> <- IO.get_env(name)")
w("    return env_nat.fin(r, dflt)")
w("")
w("def run(g: Bool, +n: Nat, +fd: Nat, +k: Nat) -> U32:")
w("  match g:")
w("    case True{}:")
w("      tree!(fd, Nat.pow(2n, Nat.sub(n, fd)), k, 0, U32.from_nat(Nat.pow(2n, n)))")
w("    case False{}:")
w("      tree(fd, Nat.pow(2n, Nat.sub(n, fd)), k, 0, U32.from_nat(Nat.pow(2n, n)))")
w("")
w("def bench(+mode: String, +n: Nat, +fd: Nat, +k: Nat) -> IO(Unit):")
w("  do IO<Unit>:")
w("    t0 : Nat <- IO.now()")
w("    x : U32 = run(String.eq(mode, \"gpu\"), n, fd, k)")
w("    t1 : Nat <- IO.now()")
w("    IO.print(mode ++ \" N=\" ++ Nat.show(n) ++ \" FD=\" ++ Nat.show(fd) ++ \" K=\" ++ Nat.show(k) ++ \" xor=\" ++ U32.show(x) ++ \" ms=\" ++ Nat.show(Nat.sub(t1, t0)))")
w("")
w("def dispatch(is_check: Bool, +mode: String, +n: Nat, +fd: Nat, +k: Nat, +cnt: Nat) -> IO(Unit):")
w("  match is_check:")
w("    case True{}:")
w("      check(cnt, 0)")
w("    case False{}:")
w("      bench(mode, n, fd, k)")
w("")
w("def main() -> IO(Unit):")
w("  do IO<Unit>:")
w("    +mode : String <- IO.try(String, IO.get_env(\"MODE\"))")
w("    +n : Nat <- env_nat(\"N\", 16n)")
w("    +fd : Nat <- env_nat(\"FD\", 10n)")
w("    +k : Nat <- env_nat(\"K\", 1n)")
w("    +cnt : Nat <- env_nat(\"CHECK\", 128n)")
w("    dispatch(String.eq(mode, \"check\"), mode, n, fd, k, cnt)")
print("\n".join(out))
